In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/azhanhussain/Developer/python-revision_DE/pr-venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/azhanhussain/Developer/python-revision_DE/pr-venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 269.6 kB/s  0:00:31m0:00:010:02
Downloading numpy-2.5.4-cp314-cp314-macosx_14_0_arm64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 1.9 MB/s  0:00:04 eta 0:00:010m
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.4 pandas-3.0.6

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
orders = pd.read_csv('orders/part-00000', header=None)

In [4]:
orders.head

<bound method NDFrame.head of            0                      1      2                3
0          1  2013-07-25 00:00:00.0  11599           CLOSED
1          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
2          3  2013-07-25 00:00:00.0  12111         COMPLETE
3          4  2013-07-25 00:00:00.0   8827           CLOSED
4          5  2013-07-25 00:00:00.0  11318         COMPLETE
...      ...                    ...    ...              ...
68878  68879  2014-07-09 00:00:00.0    778         COMPLETE
68879  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68880  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68881  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68882  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68883 rows x 4 columns]>

In [18]:
orders.\
    groupby('order_status')['order_id'].\
        agg(order_count='count')

                 order_count
order_status
CANCELED                1428
CLOSED                  7556
COMPLETE               22899
ON_HOLD                 3798
PAYMENT_REVIEW           729
PENDING                 7610
PENDING_PAYMENT        15030
PROCESSING              8275
SUSPECTED_FRAUD         1558

In [15]:
orders.groupby('order_status').count()

                 order_id  order_date  order_customer_id
order_status
CANCELED             1428        1428               1428
CLOSED               7556        7556               7556
COMPLETE            22899       22899              22899
ON_HOLD              3798        3798               3798
PAYMENT_REVIEW        729         729                729
PENDING              7610        7610               7610
PENDING_PAYMENT     15030       15030              15030
PROCESSING           8275        8275               8275
SUSPECTED_FRAUD      1558        1558               1558